name = "miniflare"
version = "0.1.0"
target = "javascript"

description = "Miniflare is a simulator for developing and testing Cloudflare Workers"
licences = ["Apache-2.0"]
repository = { type = "github", user = "crowdhailer", repo = "plinth_cloudflare", path = "miniflare" }

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_javascript = ">= 1.0.0 and < 2.0.0"
gleam_fetch = ">= 1.3.0 and < 2.0.0"
gleam_http = ">= 4.1.0 and < 5.0.0"
plinth_cloudflare = ">= 1.1.0 and < 2.0.0"
gleam_json = ">= 3.0.2 and < 4.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
conversation = ">= 2.0.2 and < 3.0.0"
