name = "plinth_cloudflare"
version = "1.0.0"
target = "javascript"

description = "Run you Gleam programs on Cloudflare's 'World Computer'/Developer Platform"
licences = ["Apache-2.0"]
repository = { type = "github", user = "crowdhailer", repo = "plinth_cloudflare" }

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_json = ">= 3.0.2 and < 4.0.0"
gleam_javascript = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
